---

- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ kubernetes.token }} \
                 {{kubernetes.master_ip}}:6443 \
                 --discovery-token-unsafe-skip-ca-verification
  register: join_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
